//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by scb.rc
//
#define IDINTERRUPT                     3
#define ID_CRIB_CLEAR                   3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SCB_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDR_MAINMENU                    129
#define IDD_NGRAPH_FILE_DIALOG          132
#define IDD_FIX_KEY_DIALOG              134
#define IDD_CRIB_DIALOG                 136
#define IDC_CIPHER                      1000
#define IDC_PLAIN                       1001
#define IDC_TRIGRAPHS                   1003
#define IDC_TETRAGRAPHS                 1004
#define IDC_NGRAPHS                     1005
#define IDC_NGRAPH_LENGTH               1006
#define IDC_NGRAPH_FILE                 1006
#define IDQUIT                          1007
#define IDC_NGRAPH_LEN                  1007
#define ID_SOLVE                        1008
#define IDC_KEY                         1009
#define ID_INTERRUPT                    1010
#define IDC_KEYS_CHECKED                1011
#define ID_STOP                         1012
#define IDC_SAMPLE_FILE                 1012
#define ID_RESUME                       1013
#define IDC_BROWSE_SAMPLE_FILE          1014
#define ID_CLEAR                        1014
#define IDC_BROWSE_NGRAPH_FILE          1015
#define IDC_NGRAPH_PROGRESS             1016
#define ID_CREATE_NGRAPH_FILE           1017
#define IDDONE                          1018
#define IDC_PROGRESS_TEXT               1019
#define IDC_CIPHER_FILENAME             1020
#define IDC_PHI_VALUE                   1021
#define IDC_SCORE                       1022
#define IDC_EDIT1                       1023
#define IDC_EDIT2                       1024
#define IDC_EDIT3                       1025
#define IDC_EDIT4                       1026
#define IDC_EDIT5                       1027
#define IDC_EDIT6                       1028
#define IDC_EDIT7                       1029
#define IDC_EDIT8                       1030
#define IDC_EDIT9                       1031
#define IDC_EDIT10                      1032
#define IDC_EDIT11                      1033
#define IDC_EDIT12                      1034
#define IDC_EDIT13                      1035
#define IDC_EDIT14                      1036
#define IDC_EDIT15                      1037
#define IDC_EDIT16                      1038
#define IDC_EDIT17                      1039
#define IDC_EDIT18                      1040
#define IDC_EDIT19                      1041
#define IDC_EDIT20                      1042
#define IDC_EDIT21                      1043
#define IDC_EDIT22                      1044
#define IDC_EDIT23                      1045
#define IDC_EDIT24                      1046
#define IDC_EDIT25                      1047
#define IDC_EDIT26                      1048
#define IDC_STATIC1                     1050
#define IDC_STATIC2                     1051
#define IDC_STATIC3                     1052
#define IDC_STATIC4                     1053
#define IDC_STATIC5                     1054
#define IDC_STATIC6                     1055
#define IDC_STATIC7                     1056
#define IDC_STATIC8                     1057
#define IDC_STATIC9                     1058
#define IDC_STATIC10                    1059
#define IDC_STATIC11                    1060
#define IDC_STATIC12                    1061
#define IDC_STATIC13                    1062
#define IDC_STATIC14                    1063
#define IDC_STATIC15                    1064
#define IDC_STATIC16                    1065
#define IDC_STATIC17                    1066
#define IDC_STATIC18                    1067
#define IDC_STATIC19                    1068
#define IDC_STATIC20                    1069
#define IDC_STATIC21                    1070
#define IDC_STATIC22                    1071
#define IDC_STATIC23                    1072
#define IDC_STATIC24                    1073
#define IDC_STATIC25                    1074
#define IDC_STATIC26                    1075
#define IDC_SPACES                      1077
#define IDC_CRIB_CIPHER                 1079
#define IDC_CRIB_PLAIN                  1080
#define IDC_CRIB_CRIB                   1081
#define IDC_CRIB_MOVE_RIGHT             1082
#define IDC_CRIB_KEY                    1083
#define IDC_CRIB_NEXT_LEFT              1084
#define IDC_CRIB_NEXT_RIGHT             1085
#define ID_FILE_EXIT                    32773
#define ID_HELP_ABOUTSECRETCODEBREAKER  32774
#define ID_TOOLS_CREATENGRAPHFILE       32775
#define IDM_SET_NGRAPH_FILE             32777
#define IDM_FILE_OPEN                   32778
#define ID_VIEW_OUTPUT_FORMAT_PRESERVE  32783
#define ID_TOOLS_FIXKEY                 32784
#define ID_HELP_INSTRUCTIONS            32785
#define ID_VIEW_REMOVEPUNCTUATION       32786
#define ID_HELP_THEORY                  32787
#define ID_TOOLS_CRIBBING               32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
